generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NewsItem
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user:                  { label: Reporter }
      filter:
        class: false
      list:
        title:                  News Items
        display:                [heading, blurb]
        sort:                   [heading, asc]
        batch_actions:          []
        object_actions:        
          _edit: ~
          _delete: ~
        max_per_page:			      10
        actions:
          _new: ~  
      form:
        display:        
          "Details":            [heading, blurb, body, is_published, lock_until, lock_after]
      edit:
        actions:          
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []