# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [elements.css, tutorplus.css, left-menu.css, form.css, symfony.css, jquery.simple-modal.css, jquery-ui.css, jquery-date-picker.css, /tiny_mce/themes/simple/skins/default/ui.css, jquery.simple-modal.css, colorbox/jquery.colorbox.css]

  javascripts:    [jquery-1.6.2.min.js, jquery.form.js, jquery/jquery.validate.min.js, /tiny_mce/tiny_mce.js, tutorplus.js, jquery.treeview.js, jquery.number_format.js, jquery.validate.numeric.js, jquery-ui.min.js, jquery.elastic.js, jquery.colorbox-min.js]

  has_layout:     true
  layout:         layout
  
  newSuccess:
    layout: false
  
  editSuccess:
    layout: false