generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CalendarEventAttendee
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          calendar_event_attendee
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      filter:
        class: false
      list:
        title:             Calendar Event Attendees
        display:           [ calendar_event_id, user_id, status, comment ]
        sort:              [ status, asc ]
        batch_actions:     [ ]
        max_per_page:			 10
        actions:
          _new: ~
      edit:
      new: