generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProfileQualification
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profile_qualification
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~      
      edit:
        actions:
          cancel:            []
          done:              []
          _save:             []
      new:
        actions:
          cancel:            []
          _save:             []
