generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Application
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          application
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      form:
        class:               ApplicationForm
        display:            
         "User Details":     [first_name, last_name, middle_name, email, gender, status]
         "Contact Details":  [phone_mobile, phone_work, phone_home, address_line_one, address_line_two, postcode, city, state_province_id, country_id]
         "Academic Details": [program_id, academic_period_id]
      filter:
        class: false
      list:
        title:               Applications
        display:             [first_name, last_name, middle_name, status, gender,phone_mobile, phone_work, phone_home, postcode, city]
        sort:                [first_name, last_name, asc]
        batch_actions:       []
        max_per_page:			   10
        actions:
          _new: ~
      edit:
      new: