generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Profile
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          instructor_enroll
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        birth_date:          { label: DOB }
      actions:               ~
      form:
        class:               InstructorEnrollForm
        display:            
         "Personal Details": [ first_name, last_name, birth_date, institution_id ]
         "Credentials":      [ email, password, password_confirmation ]
      filter:
        class:               false
      new:
        title:               "Sign Up"
        actions:
          _save:             { label: "Enroll" }