generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CalendarEvent
    theme:                 ecollegeplus2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          calendar_event
    with_doctrine_route:   true
    actions_base_class:    sfActions
    
    config:
      actions: ~
      fields:
        name:              { label: Title }
        location:          { label: Where }
        from_date:         { label: From }
        to_date:           { label: To }
        user:              { label: Organiser }
      filter:
        class:              false        
      form:
        display:            
         "Event Details":   [ name, calendar_id, from_date, to_date, location, description, is_personal, notify_changes ]
         "Event Attendees": [ _attendees ]
      list:
        title:              Events
        display:            [ name, user, when, location ]
        sort:               [ name, asc ]
        batch_actions:      [ ]
        max_per_page:			  10
        actions:
          _new:             { label: "+ Add Event" }
      edit:
        title:              Edit Event ~ %%name%%
        actions:
          cancel:           []
          done:             []
          _save:            []
      new:
        title:              New Event
        actions:
          cancel:           []
          _save:            []