generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Staff
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          staff_staff_contact
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~      
      edit:
        actions:
          _cancel:              []
          _save:                []
          _done:                []
      new:
        actions:
          _cancel:              []
          _save:                []
