generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Calendar
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          calendar
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      filter:
        class: false
      list:
        title:             Calendars
        display:           [ name, color, description, is_public ]
        sort:              [ name, asc ]
        batch_actions:     []
        max_per_page:			 10
        actions:
          _new:            { label: "+ Add Calendar" }
      edit:
        title:             Edit Calendar
        display:           [ name, description, type, is_public, _color ]
        actions:
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Calendar
        display:           [ name, description, type, is_public, _color ]
        actions:
          cancel:          []
          _save:           []