generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProgramLevel
    theme:                 popup
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          program_level
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      filter:
        class: false
      list:
        title:             Program Levels
        display:           [ name ]
        sort:              [ name, asc ]
        batch_actions:     [ ]
        max_per_page:			 10
        actions:
          _new:              ~
      edit:
        actions:
          cancel:            []
          done:              []
          _save:             []
      new:
        actions:
          cancel:            []
          _save:             []