generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contact
    theme:                 ecollegeplus2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:                ~
      fields:
        #from_email:          { label: From }
        #created_at:          { label: Date }
        #to_email:            { label: To }
        #cc_email:            { label: Cc }
        #bcc_email:           { label: Bcc }
      form:
        class:                ContactForm
      filter:
        class: false
      list:
        title:                Contacts
        display:              [first_name, last_name, email_address, phone_mobile]
        sort:                 [first_name, last_name, email_address, phone_mobile, asc]
        object_actions:       []
        batch_actions:        []
        max_per_page:			    1
        actions:
          _new:               ~