generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CourseLink
    theme:                 ecollegeplus
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          course_link
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      filter:
        class: false
      list:
        title:             Course Links
        display:           [name, url]
        sort:              [name, url, asc]
        batch_actions:     []
        max_per_page:			 10
        actions:
          _new:                 ~
      edit:
        actions:
          _cancel:              []
          _save:                []
          _done:                []
      new:
        actions:
          _cancel:              []
          _save:                []