generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CourseReadingItem
    theme:                 popup
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          course_reading_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        actions:
          cancel:               [ ]
          done:                 [ ]
          save:                 [ ]
      new:
        actions:
          cancel:               [ ]
          _save:                [ ]