generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Announcement
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          course_announcement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user:                   { label: Announcer }
      filter:
        class: false
      list:
        title:                  Announcements
        display:                [ subject, user ]
        sort:                   [ subject, asc ]
        batch_actions:          []
        object_actions:        
          _edit: ~
          _delete: ~
        max_per_page:	        10
        actions:
          _new:                 { label: "+ New Announcement" }
      form:
        display:
          "Details":            [ subject, message, is_published, lock_until, lock_after ]
      edit:
        actions:          
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []
