secure:
  dashboard:  
    details:                          { route: dashboard, label: Dashboard }
    type:                             Many
    children:                         {}
  timeline:                          
    details:                          { route: activity_feed, label: Timeline }
    type:                             One
    children:
      timeline:                                     
        details:                      { route: activity_feed, label: Timeline }
        credentials:                  [ student, instructor, staff ]
        children:
          activity_feeds:             { route: activity_feed, label: "Activity Feeds" }
          news_items:                 { route: news_item, label: "News Items" }
          announcements:              { route: announcement, label: "Announcements" }
  courses:                          
    details:                          { route: course_explorer, label: Courses }
    type:                             One
    children:
      courses:                                        
        details:                      { route: my_courses, label: "Courses" }
        credentials:                  [ student, instructor, staff ]
        children:
          course_explorer:            { route: course_explorer, label: "Course Explorer" }
          my_courses:                 { route: my_courses, label: "My Courses" }
      my_course:                                        
        details:                      { route: course_show, label: "Course Home" }
        credentials:                  [ student, instructor, staff ]
        children:
          course_info:                { route: course_show, param: slug,  label: "Course Info" }
          announcements:              { route: course_announcement, label: "Announcements" }
          course_participants:        { route: course_participant, label: "Course Peers" }
          course_calendar:            { route: course_calendar, label: "Calendar" }
          assignments:                { route: assignment, label: "Assignments" }
          #assessment_types:           { route: assessment_type, label: "Assessment Types" }
          course_discussion:          { route: course_discussion, label: "Discussions" }
          course_files:               { route: course_file, label: "Course Files" }
      my_assignment:                                        
        details:                      { route: assignment_show, label: "Assignment Home" }
        credentials:                  [ student, instructor, staff ]
        children:
          assignment_info:            { route: assignment_show, label: "Assignment Info" }
          assignment_discussion:      { route: course_discussion, label: "Discussions" }
  discussions:                          
    details:                          { route: discussion_explorer, label: Discussions }
    type:                             One
    children:
      discussions:                                     
        details:                      { route: discussion_explorer, label: "Discussions" }
        credentials:                  [ student, instructor, staff ]
        children:
          discussion_explorer:        { route: discussion_explorer, label: "Discussion Explorer" }
          my_discussions:             { route: my_discussions, label: "My Discussions" }
  calendar:                          
    details:                          { route: my_schedule, label: Calendar }
    type:                             One
    children:
      my_calendar:                                        
        details:                      { route: my_schedule, label: "Calendar" }
        children:
          my_schedule:                { route: my_schedule, label: "My Schedule" }
          calendar_events:            { route: calendar_event, label: "Events" }
          calendars:                  { route: calendar, label: "Calendars" }
  profile:                          
    details:                          { route: profile_timeline, label: Profile }
    type:                             One
    param:                            slug
    children:
      my_profile:                   
        details:                      { route: profile_timeline, label: "Profile" }
        credentials:                  [ student, instructor, staff ]
        param:                        slug
        children:
          my_timeline:                { route: profile_timeline, label: "Timeline" }                    
          my_info:                    { route: profile_show, param: slug, label: "Public Info" }
          my_peers:                   { route: profile_peers, label: "Peers" }
          my_awards:                  { route: profile_award, label: "Awards" }
          my_qualifications:          { route: profile_qualification, label: "Qualifications" }
          my_account_settings:        { route: profile_account_settings, command: ignore, label: "Account Settings" }
          my_contact_details:         { route: profile_contact_details, command: ignore, label: "Contact Details" }
          my_notification_settings:   { route: notification_settings, command: ignore, label: "Notification Settings" }
  peers:   
    details:                          { route:  peer_students, label: Peers }
    type:                             One
    children:
      peers:                   
        details:                      { route: peer_students, label: "Peers" }
        credentials:                  [ student, instructor, staff ]
        children:                    
          student_peers:              { route: peer_students, label: "Students" }
          instructor_peers:           { route: peer_instructors, label: "Instructors" }
          suggested_peers:            { route: peer_suggested, label: "Suggestions" }
          find_peers:                 { route: peer_find, label: "Find Peers" }
  messaging:                          
    details:                          { route: message_inbox, label: Messaging }
    type:                             One
    children:
      my_messages:                    
        details:                      { route: message_inbox, label: "Messaging" }
        credentials:                  [ student, instructor, staff ]
        children:
          message_inbox:              { route: message_inbox, label: "Inbox" }
          message_sent:               { route: message_sent, label: "Sent" }
          message_draft:              { route: message_draft, label: "Drafts" }
          message_trash:              { route: message_trash, label: "Trash" }
  settings:    
    details:                          { route: course, label: Settings }
    type:                             Many
    children:
      academic_settings:                   
        details:                      { route: course, label: "Academic Settings" }
        credentials:                  [ administrator ]
        children:                    
          institutions:               { route: institution, label: Institutions }
          faculties:                  { route: faculty, label: "Faculties" }
          departments:                { route: department, label: "Departments" }
          program_levels:             { route: program_level, label: "Program Levels" }
          programmes:                 { route: program, label: "Programmes" }
          courses:                    { route: course, label: Courses }
          academic_years:             { route: academic_year, label: "Academic Years" }
          academic_periods:           { route: academic_period, label: "Academic Periods" }
      access_settings:                    
        details:                      { route: student, label: "Access Settings" }
        credentials:                  [ administrator ]
        children:
          students:                   { route: student, label: "Students" }
          instructors:                { route: instructor, label: "Instructors" }
          staff:                      { route: staff, label: "Staff" }
          groups:                     { route: profile_group, label: "Groups" }
          permissions:                { route: profile_permission, label: "Permissions" }
      communication_settings:                    
        details:                      { route: email_template, label: "Communication Settings" }
        credentials:                  [ administrator ]
        children:
          email_templates:            { route: email_template, label: "Email Templates" }
          mailing_lists:              { route: mailing_list, label: "Mailing Lists" }
          activity_templates:         { route: activity_template, label: "Activity Templates" }
          discussion_types:           { route: discussion_type, label: "Discussion Types" }
          faqs:                       { route: faq, label: "Faqs" }
      location_settings:                    
        details:                      { route: country, label: "Location Settings" }
        credentials:                  [ administrator ]
        children:
          countries:                  { route: country, label: "Countries" }
          state_provincies:           { route: state_province, label: "State Provinces" }
          buildings:                  { route: building, label: "Buildings" }
          campuses:                   { route: campus, label: "Campuses" }
          rooms:                      { route: room, label: "Rooms" }
#  payments:
#    details:                        { route: payment, label: Payments }
#    type:                           Many
#    children:
#      history:
#        details:                    { route: activity_feed, label: "History" }
#        credentials:                [ staff ]
#        children:
#          received_payments:        { route: payment, label: "Received" }
#      plans:
#        details:                    { route: payment_scheme, label: "Plans" }
#        credentials:                [ staff ]
#        children:
#          payment_scheme:           { route: payment_scheme, label: "Schemes" }
public:
  home:  
    details:                        { route: home, label: Home }
  courses:  
    details:                        { route: courses, label: Courses }
  story:  
    details:                        { route: story, label: "Our Story" }
  institutions:  
    details:                        { route: institutions, label: Institutions }
  instructors:  
    details:                        { route: instructors, label: Instructors }
  leadership:  
    details:                        { route: leadership, label: "Leadership" }
  faqs:  
    details:                        { route: faqs, label: Faqs }
  contact_us:  
    details:                        { route: contact_us, label: "Contact Us" }