generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Student
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_enroll
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        number:              { label: "Unisa Student Number" }
        password_again:      { label: "Confirm password" }
        permissions_list:    { lable: Roles }

      actions:               ~
      form:
        class:               StudentRegisterForm
        display:            
         "Your Personal Details":        [first_name, last_name, number, email_address, mobile_phone, country_id, state_province_id]
         "Tutorial Enrollment Details":  [year, semester, department_1, course_1, department_2, course_2, department_3, course_3]
      filter:
        class: false
      list:
        title:               Students
        display:             [first_name, last_name, email_address, number, status, enrollment, gender]
        sort:                [number, asc]
        batch_actions:       []
        max_per_page:			   10
        actions:
          _new:              { label: "+ Add Student" }
      edit:
        title:               Edit Student ~ %%first_name%% %%last_name%%
        actions:
          _academic:         []
          _contact:          []
          cancel:            []
          done:              []
          _save:             []
      new:
        title:               "Enroll now for all your Unisa modules tutorials!"
        actions:
          cancel:            []
          _save:             { label: "Enroll Now!" }