generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DiscussionPost
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          discussion_topic_message
    with_doctrine_route:   true
    actions_base_class:    sfActions
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      form:
        display:           [message]
      filter:
        class: false
      list:
        title:             My Topic Messages
        display:           [message]
        sort:              [name, asc]
        batch_actions:     []
        max_per_page:			 10
        actions:
          _new:            []
      edit:
        title:             Edit Discussion: %%name%%
        actions:
          _delete:         []
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Discussion
        actions:
          _save:           [label: Send]