generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NotificationSettings
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notification_settings
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:                  ~      
      fields:
        email:                  { label: "I'm sent a direct message" }
        reply:                  { label: "I'm sent a reply or mentioned" }
        request:                { label: "I'm followed by someone new" }
        news_alerts:            { label: "There's any news alerts" }
        announcement_alerts:    { label: "There's any announcement alerts" }
        event_alerts:           { label: "There's any event alerts" }
        peer_activities:        { label: "There's any new peer activities" }
        discussion_updates:     { label: "My discussions or topics are updated" }
        course_updates:         { label: "There's any course material changes/uploads" }
        assignment_due:         { label: "Assignments are due for submissions" }
        system_updates:         { label: "New changes have been applied to the TutorPlus system" }
        system_maintenance:     { label: "System is going to be down for maintenance purposes" }
        
      form:
        display:            
         "Messages - Receive notification when:":            [email, reply]
         "Alerts - Receive notification when:":              [news_alerts, announcement_alerts, event_alerts]
         "Activities - Receive notification when:":          [peer_activities, discussion_updates, course_updates, assignment_due]
         "Updates - Receive notification when:":             [system_updates, system_maintenance]
      filter:
        class: false
      list:
        title:                  Notification Settings
        sort:                   [email, asc]
        batch_actions:          []
        object_actions:        
          _edit: ~
          _delete: ~
        max_per_page:			      10
        actions:
          _new: ~
      edit:
        title:                  Edit Notification Settings
        actions:
          _save:                []