generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Program
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          program
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      form:
        display:            
         "Program Details": [name, abbreviation, description, type, department_id, program_level_id, code]
      filter:
        class: false
      list:
        title:             Programs
        display:           [name, abbreviation, description, type, department, program_level, code]
        sort:              [name, asc]
        batch_actions:     []
        max_per_page:			 10
        actions:
          _new: ~
      edit:
        actions:          
          cancel:               []
          done:                 []
          _save:                []
      new:
        actions:
          cancel:               []
          _save:                []