generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DiscussionPeer
    theme:                 normal
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          discussion_peer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user:                         { label: Peer }
        subscription_type:            { label: Subscription }
        membership_type:              { label: Membership }

      form:
        display:            
         "Parcipant Details":          [ nickname ]
         "Membership Settings":        [ subscription_type ]
      filter:
        class:                         false
      list:
        title:                         DiscussionGroup Members
        display:                       [ =user, nickname, membership_type_display, status_display, is_removed ]
        sort:                          [ nickname, asc ]
        batch_actions:                 []
        max_per_page:			             10
        object_actions:
          _edit:                       []
        actions:
          listDiscussionGroup:         { label: < My Discussion }
          _new:                        { label: + Invite Peers }
      edit:
        title:                         Edit Membership
        actions:
          cancel:                      []
          done:                        []
          _save:                       []
      new:
        title:                         Join Group
        actions:
          cancel:                      []
          _save:                       []