generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Discussion
    theme:                 popup
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          discussion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user:              { label: Initiator }
        nb_members:        { label: Members }
        nb_topics:         { label: Total topics }
      form:
        display:           [name, description, access_level]
      filter:
        class: false
      list:
        title:             My Discussions
        display:           [=name, user, access_level, nb_topics, nb_members, last_visit]
        sort:              [name, asc]
        batch_actions:     []
        object_actions:     
          _edit:           []
        max_per_page:			 10
        actions:
          _new:            { label: "+ New Discussion" }
      edit:
        title:             Edit Discussion
        actions:
          cancel:          []
          done:            []
          _save:           []
      new:
        title:             New Discussion
        actions:
          cancel:          []
          _save:           [label: Proceed]