generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Student
    theme:                 ecollegeplus2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        courses_list:        { label: Courses }
        password_again:      { label: "Confirm password" }
        permissions_list:    { lable: Roles }
      actions: ~
      form:
        class:               StudentForm
        display:            
         "Student Details":  [first_name, middle_name, last_name, number, date_of_birth, high_school, current_study, studied_at, gender, enrollment, status]
         "Account Details":  [username, email_address, password, password_again, is_active]
      filter:
        class: false
      list:
        title:               Students
        display:             [first_name, last_name, email_address, number, status, enrollment, gender, _is_active]
        sort:                [number, asc]
        batch_actions:       []
        max_per_page:			   10
        actions:
          _new:              { label: "+ Add Student" }
      edit:
        title:               Edit Student ~ %%first_name%% %%last_name%%
        actions:
          cancel:            []
          done:              []
          _save:             []
      new:
        title:               New Student
        actions:
          cancel:            []
          _save:             []